// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9JnKYH7QYQSIdFEv8CHF_MTtcjU52re8',
    appId: '1:528777529072:web:de8d9a91f6f4b5aa46e435',
    messagingSenderId: '528777529072',
    projectId: 'winksy-d28f6',
    authDomain: 'winksy-d28f6.firebaseapp.com',
    storageBucket: 'winksy-d28f6.firebasestorage.app',
    measurementId: 'G-B62NJZQ7EN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7WZvMvHxttlh5f-wIVxiG3ZRxhVAexv8',
    appId: '1:528777529072:android:5efa2c8d1c873dda46e435',
    messagingSenderId: '528777529072',
    projectId: 'winksy-d28f6',
    storageBucket: 'winksy-d28f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQngcAfhHNQELPHhRWhLsG6fLWcD3rpp4',
    appId: '1:528777529072:ios:ffe1539a0a46995a46e435',
    messagingSenderId: '528777529072',
    projectId: 'winksy-d28f6',
    storageBucket: 'winksy-d28f6.firebasestorage.app',
    androidClientId: '528777529072-ealbu802gd3882qt37te5ej5ber8mq1h.apps.googleusercontent.com',
    iosClientId: '528777529072-8a2ogu7b0gori2edm53bj0ji7fkirnnf.apps.googleusercontent.com',
    iosBundleId: 'ir.cyren.winksy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQngcAfhHNQELPHhRWhLsG6fLWcD3rpp4',
    appId: '1:528777529072:ios:ffe1539a0a46995a46e435',
    messagingSenderId: '528777529072',
    projectId: 'winksy-d28f6',
    storageBucket: 'winksy-d28f6.firebasestorage.app',
    androidClientId: '528777529072-ealbu802gd3882qt37te5ej5ber8mq1h.apps.googleusercontent.com',
    iosClientId: '528777529072-8a2ogu7b0gori2edm53bj0ji7fkirnnf.apps.googleusercontent.com',
    iosBundleId: 'ir.cyren.winksy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9JnKYH7QYQSIdFEv8CHF_MTtcjU52re8',
    appId: '1:528777529072:web:5b16261ca288169846e435',
    messagingSenderId: '528777529072',
    projectId: 'winksy-d28f6',
    authDomain: 'winksy-d28f6.firebaseapp.com',
    storageBucket: 'winksy-d28f6.firebasestorage.app',
    measurementId: 'G-C7GCF1ET2C',
  );

}